modules/admin/controllers/InvestCustomerController.php
<?php

namespace app\modules\admin\controllers;

use app\components\controllers\AdminBaseController;
use app\forms\InvestRegisterForm;
use app\models\CustomerToken;
use app\models\investments\InvestCustomerRequest;
use app\models\LogAction;
use app\models\logs\AdminLogAction;
use app\models\searchs\InvestCustomerPackageHistorySearch;
use app\modules\admin\forms\ChangePasswordForm;
use app\modules\admin\forms\customers\TransferTokenForm;
use app\modules\admin\forms\tools\ChangeParentCustomer;
use Yii;
use app\models\investments\InvestCustomer;
use app\modules\admin\forms\InvestCustomerSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * InvestCustomerController implements the CRUD actions for InvestCustomer model.
 */
class InvestCustomerController extends AdminBaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all InvestCustomer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new InvestCustomerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single InvestCustomer model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new InvestCustomer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($ref = 0)
    {
        $model = new InvestRegisterForm();
        $model->scenario = $model::SCENARIO_ADMIN_REGISTER;
        $listCustomer = null;
        if ($ref) {
            $customerInvited = InvestCustomer::findByRefCode($ref);
            if (!$customerInvited) {
                throw new NotFoundHttpException('Tài khoản giới thiệu không hợp lệ.');
            }
            $model->customer_parent_id = $customerInvited->id;
        } else {
            $listCustomer = InvestCustomer::getAllCustomer(0, InvestCustomer::TYPE_ADMIN);
        }

        if ($model->load(Yii::$app->request->post())) {
            $customer = $model->createCustomer(true);
            $errors = $customer->getErrors();
            if (empty($errors)) {
                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_CREATE, $customer->attributes);
                //Add case
                if ($customer->addInvestCustomerCase()) {
//                    LogAction::logAdmin($customer->id, $customer::tableName(), LogAction::TYPE_USER_CREATE, $customer->getAttributes(['id', 'username', 'full_name', 'sex', 'phone', 'email', 'date_join', 'created_at']));
                } else {
                    //Nếu có lỗi xóa tài khoản đi
                    Yii::$app->session->setFlash('error', 'Không tạo được tài khoản invest');
                    $customer->delete();
                }
                return $this->redirect(['index']);
            } else {
                if (!empty($errors)) {
                    $error = '';
                    foreach ($customer->getErrors() as $val) {
                        $error .= isset($val[0]) ? $val[0] : '';
                    }
                    AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_ERROR, $customer->getErrors());
                    Yii::$app->session->setFlash('error', $error);
                    //print_r($customer->getErrors());
                }
            }

        }
        return $this->render('create', [
            'model' => $model,
            'listCustomer' => $listCustomer
        ]);
    }

    public function actionUpdate($id)
    {
        /**
         * @var $model InvestCustomer
         */
        $model = $this->findModel($id);
        $listCustomer = InvestCustomer::getAllCustomer(0, InvestCustomer::TYPE_ADMIN);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save(true, ["full_name", "dob", "phone", "email", "nation", "identity_card", "updated_at"])) {
                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_UPDATE, $model->attributes);
                return $this->redirect(['index']);
            }
        }
        return $this->render('update', [
            'model' => $model,
            'listCustomer' => $listCustomer
        ]);
    }

    public function actionActive($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->request->post()) {
            $active = Yii::$app->request->post('active', '');
            if ($active == 'active') {
                if ($model->setActive()) {
                    AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_UPDATE, $model->attributes);
                    Yii::$app->session->setFlash('success', 'Active user "' . $model->username . '" Success.');
                    return $this->redirect(['index']);
                } else {
                    Yii::$app->session->setFlash('error', 'Active user "' . $model->username . '" Error.');
                }
            }
        }
        return $this->render('active', ['model' => $model]);
    }

    public function actionUnactive($id)
    {
        $model = $this->findModel($id);
        if ($model->is_active == InvestCustomer::IS_ACTIVE_COMPLETED) {
            $model->is_active = InvestCustomer::IS_ACTIVE_PENDING;
            if ($model->save(true, ['is_active', 'updated_at'])) {
                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_UPDATE, $model->attributes);
                Yii::$app->session->setFlash('success', 'Unactive "' . $model->username . '" Successfull.');
                return $this->redirect(['index']);
            } else {
                Yii::$app->session->setFlash('error', 'Unactive "' . $model->username . '" Error.');
            }
        }
        return false;
    }

    public function actionLockUser($id)
    {
        $model = $this->findModel($id);
        if ($model->status == InvestCustomer::STATUS_ACTIVE) {
            $model->status = InvestCustomer::STATUS_INACTIVE;
            if ($model->save(true, ['status', 'updated_at'])) {
                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_UPDATE, $model->attributes);
                Yii::$app->session->setFlash('success', 'Khóa tài khoản "' . $model->username . '" thành công.');
                return $this->redirect(['index']);
            } else {
                Yii::$app->session->setFlash('error', 'Khóa tài khoản "' . $model->username . '" không thành công.');
            }
        }
        if ($model->status == InvestCustomer::STATUS_INACTIVE) {
            $model->status = InvestCustomer::STATUS_ACTIVE;
            if ($model->save(true, ['status', 'updated_at'])) {
                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_UPDATE, $model->attributes);
                Yii::$app->session->setFlash('success', 'Mở khóa tài khoản "' . $model->username . '" thành công.');
                return $this->redirect(['index']);
            } else {
                Yii::$app->session->setFlash('error', 'Mở khóa tài khoản "' . $model->username . '" không thành công.');
            }
        }
        return $this->render('active', ['model' => $model]);
    }

    /**
     * Deletes an existing InvestCustomer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
//        $this->findModel($id)->delete();
        $model->is_deleted = $model::IS_DELETED;
        LogAction::logAdmin($model->id, $model::tableName(), LogAction::TYPE_USER_DELETE, $model->getAttributes(["id", "is_deleted", "updated_at"]));
        $model->save(true, ['is_deleted', 'updated_at']);
        AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_DELETE, $model->attributes);
//        InvestCustomer::saveCustomerCaseDelete($model->id, $model->parent_id);
        return $this->redirect(['index']);
    }

    public function actionExportExcel()
    {
        set_time_limit(1000);
        if (!Yii::$app->request->isPost) {
            throw new \yii\web\MethodNotAllowedHttpException('Truy cập không hợp lệ.');
        }

        $searchModel = new InvestCustomerSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);
        $dataProvider->pagination = false;
        $models = $dataProvider->getModels();

        // Load excel template
        $phpExcel = \PHPExcel_IOFactory::load(\Yii::getAlias('@app/web/template/invest-customer-list.xlsx'));

        $phpExcel->setActiveSheetIndex(0);

        // Dòng bắt đầu fill data
        $baseRow = 7;

        $totalRows = count($models);

        /* @var $itemModel InvestCustomerSearch */
        foreach ($models as $n => $itemModel) {
            $row = $baseRow + $n;
            $phpExcel->getActiveSheet()->insertNewRowBefore($row, 1);
            //echo '<pre>';var_dump($itemModel);die;
            $phpExcel->getActiveSheet()
                ->setCellValue('A' . $row, $n + 1)
                ->setCellValue('B' . $row, $itemModel->username)
                ->setCellValue('C' . $row, $itemModel->full_name)
                ->setCellValue('D' . $row, $itemModel->email)
                ->setCellValue('E' . $row, $itemModel->phone)
                ->setCellValue('F' . $row, InvestCustomer::getName($itemModel->parent_id))

modules/admin/views/invest-customer/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use app\models\Package;
use yii\helpers\ArrayHelper;
use app\models\Customer;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */
/* @var $form yii\widgets\ActiveForm */


?>
<?php $form = ActiveForm::begin([]); ?>
<div class="row">
    <div class="col-sm-6">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title"><?= Yii::t('customers', 'Account') ?></h3>
            </div>
            <div class="box-body">

                <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
                <?php
                if (Yii::$app->request->get('ref', '')):
                else:
                    echo $form->field($model, 'customer_parent_id')->dropDownList(ArrayHelper::map($listCustomer, 'id', 'fullName'), ['prompt' => Yii::t('customers', ' -- Select account invited --'), 'id' => 'select-parent-customer']);
                endif;
                ?>
                <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

            </div>

        </div>
    </div>
    <div class="col-sm-6">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title"><?= Yii::t('customers', 'Profile') ?></h3>
            </div>
            <div class="box-body">
                <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>

                <?=
                $form->field($model, 'dob')->widget(DatePicker::className(), [
                    'options' => [
                        'class' => 'form-control',
                        'placeholder' => 'dd-mm-yyyy'
                    ],
                    'language' => 'vi',
                    'clientOptions' => [
                        'changeMonth' => true,
                        'changeYear' => true,
                        'yearRange' => '1960:2015'
                    ]
                ])
                ?>
                <?= $form->field($model, 'identity_card')->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'nation')->dropDownList(\app\models\investments\InvestCustomer::getNationLabels()) ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="pull-right">
            <div class="form-group">
                <label class="control-label"></label>
                <?= Html::submitButton('<span class=" fa fa-floppy-o"></span>&nbsp;' . Yii::t('customer', 'Save customer'), ['class' => 'btn btn-primary btn-sm']) ?>
            </div>
        </div>
    </div>
</div>

<?php ActiveForm::end(); ?>
<?php
\app\assets\plugins\Select2PluginAsset::register($this);
$js = <<<EOD
if($("#select-parent-customer").length >0){
    $("#select-parent-customer").select2();
 }
EOD;
$this->registerJs($js);
?>

modules/admin/views/invest-customer/_formUpdate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use app\models\Package;
use yii\helpers\ArrayHelper;
use app\models\Customer;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */
/* @var $form yii\widgets\ActiveForm */

?>
<?php $form = ActiveForm::begin([]); ?>
<div class="row">
    <div class="col-sm-6">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title"><?= Yii::t('customers', 'Account') ?></h3>
            </div>
            <div class="box-body">

                <?= $form->field($model, 'username')->textInput(['disabled' => true]) ?>
                <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

            </div>

        </div>
    </div>
    <div class="col-sm-6">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title"><?= Yii::t('customers', 'Profile') ?></h3>
            </div>
            <div class="box-body">
                <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>

                <?=
                $form->field($model, 'dob')->widget(DatePicker::className(), [
                    'options' => [
                        'class' => 'form-control',
                        'placeholder' => 'dd-mm-yyyy'
                    ],
                    'language' => 'vi',
                    'clientOptions' => [
                        'changeMonth' => true,
                        'changeYear' => true,
                        'yearRange' => '1960:2015'
                    ]
                ])
                ?>
                <?= $form->field($model, 'identity_card')->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'nation')->dropDownList(\app\models\investments\InvestCustomer::getNationLabels()) ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="pull-right">
            <div class="form-group">
                <label class="control-label"></label>
                <?= Html::submitButton('<span class=" fa fa-floppy-o"></span>&nbsp;' . Yii::t('customer', 'Save customer'), ['class' => 'btn btn-primary btn-sm']) ?>
            </div>
        </div>
    </div>
</div>

<?php ActiveForm::end(); ?>
<?php
\app\assets\plugins\Select2PluginAsset::register($this);
$js = <<<EOD
if($("#select-parent-customer").length >0){
    $("#select-parent-customer").select2();
 }
EOD;
$this->registerJs($js);
?>

modules/admin/views/invest-customer/_info.php
<?php
/**
 * Created by PhpStorm.
 * User: Dev
 * Date: 10-Jun-16
 * Time: 9:13 AM
 */
use yii\widgets\DetailView;

if ($model):
    ?>
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        'username',
        'status',
        'full_name',
        'sex',
        'phone',
        'email:email',
        'nation',
        'address',
        'created_at:datetime',
    ],
]) ?>
    <?php
    $form = \yii\widgets\ActiveForm::begin();
    ?>
    <p>
        <?= \yii\helpers\Html::submitButton('Kích hoạt tài khoản', ['name' => 'active', 'value' => 'active', 'class' => 'btn btn-sm btn-warning']) ?>
    </p>
    <?php
    \yii\widgets\ActiveForm::end();
    ?>

<?php endif; ?>

modules/admin/views/invest-customer/active.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */

$this->title = 'Kích hoạt tài khoản ' . $model->username;
//$this->params['breadcrumbs'][] = ['label' => Yii::t('customers', 'Customers'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
$this->params['pageTitle'] = $this->title;
$this->params['parentAction'] = '/admin/customer/index';
?>
<div class="customer-view">
    <?= $this->render('_info', ['model' => $model]) ?>


</div>

modules/admin/views/invest-customer/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Customer */

$this->title = Yii::t('customers', 'Create Invest Customer');
$this->params['breadcrumbs']['Invest Customers'] = \yii\helpers\Url::to(['index']);
$this->params['breadcrumbs'][] = $this->title;
$this->params['pageTitle'] = $this->title;
$this->params['parentAction'] = '/admin/invest-customer/index';
?>
<div class="customer-create">


    <?= $this->render('_form', [
        'model' => $model,
        'listCustomer' => $listCustomer
    ]) ?>

</div>

modules/admin/views/invest-customer/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use \app\models\investments\InvestCustomer;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\forms\InvestCustomerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('customers', 'Investor Customer');
$this->params['breadcrumbs'][] = $this->title;
$this->params['pageTitle'] = $this->title;
?>
<div class="box box-primary">
    <div class="box-body">
        <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    </div>
</div>
<div class="tools">
    <div class="pull-left">
        <?=
        Html::a('Export Excel', ['export-excel'] + Yii::$app->request->queryParams, [
            'class' => 'btn btn-info',
            'data-method' => 'post',
        ]);
        ?>
    </div>
    <div class="pull-right" style="margin-bottom: 20px ">
        <?= Html::a('<span class="fa fa-square-plus-o"></span>&nbsp;' . Yii::t('customers', 'Create Customer'), ['create'], ['class' => 'btn btn-success btn-sm']) ?>
    </div>
</div>


<div class="table-content" style="float: left; width: 100%;">

    <?php
    $gridColumns = [
//        ['class' => 'kartik\grid\SerialColumn',
//            'contentOptions' => ['class' => 'kartik-sheet-style'],
//            'width' => '36px',
//            'header' => '',
//            'headerOptions' => ['class' => 'kartik-sheet-style']
//        ],
        'id',
        [
            'header' => 'Message',
            'format' => 'raw',
            'value' => function ($model) {
                return Html::a('<i class="glyphicon glyphicon-envelope" style="font-size: 20px;"></i><span></span>', ['/admin/note/index'], [
                    'class' => 'add-note',
                    'data-table' => InvestCustomer::tableName(),
                    'data-id' => $model->id,
                    'data-toggle' => 'modal',
                    'data-target' => '#myModal',
                    'title' => 'Ghi chú',
                ]);
            }
        ],
        'username',
        'ref_code',
        'full_name',
        'email',
        'phone',
//        [
//            'attribute' => 'sex',
//            'format' => 'text', //raw, html
////                'filter' => Customer::getSexLabels(),
//            'content' => function ($data) {
//                $arr = Customer::getSexLabels();
//                return (isset($arr[$data->sex]) ? $arr[$data->sex] : '');
//            }
//        ],
//        [
//            'attribute' => 'package_id',
//            'format' => 'text', //raw, html
////                'filter' => ArrayHelper::map(Package::getPackages(), 'id', 'package_name'),
//            'content' => function ($data) {
//                return Package::getName($data->package_id);
//            }
//        ],
//        [
//            'attribute' => 'parent_id',
//            'format' => 'text', //raw, html
////                'filter' => ArrayHelper::map(Customer::getAllCustomer(), 'id', 'fullName'),
//            'content' => function ($data) {
//                return Customer::getName($data->parent_id);
//            }
//        ],
//        [
//            'attribute' => 'amount',
//            'content' => function ($data) {
//                return Yii::$app->formatter->asDecimal($data->amount, '1');
//            }
//        ],
        [
            'attribute' => 'is_active',
            'content' => function ($data) {
                /**
                 * @var $data InvestCustomer
                 */
                return (isset($data->getIsActiveLabels()[$data->is_active]) ? $data->getIsActiveLabels()[$data->is_active] : '--');
            }
        ],
        /*[
            'label' => 'Invest Bank Address',
            'content' => function ($data) {
                if ($data->bankAddress) {
                    return Html::a('<span class="fa fa-pencil-square-o"></span>&nbsp' . $data->bankAddress->bank_address,
                        ['update-bank-address', 'id' => $data->id],
                        [
                            'title' => 'Sửa địa chỉ nhận',
                            'class' => 'text-primary',
                        ]);
                }
                return Html::a('<span class="fa fa-plus-square-o"></span>&nbsp Add bank address ',
                    ['add-bank-address', 'id' => $data->id],
                    ['title' => 'Tạo mới địa chỉ nhận',
                        'class' => 'btn btn-success btn-flat btn-xs'
                    ]);
            }
        ],*/
        [
            'attribute' => 'created_at',
            'format' => 'text', //raw, html
            'filter' => false,
            'content' => function ($data) {
                return (isset($data->created_at) && $data->created_at > 0) ? Yii::$app->formatter->asDate($data->created_at) : '--';
            }
        ],
        [
            'class' => 'kartik\grid\ActionColumn',
            'hAlign' => 'left',
            'headerOptions' => ['width' => '150px;', 'style' => 'width: 150px;'],
            'width' => '100px',
            'contentOptions' => ['style' => 'width: 150px;'],
            'template' => '{groups}',
            'buttons' => [
                'groups' => function ($url, $data) {
                    $html = '';
                    $html .= '<div class="btn-group">';
                    $html .= '<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Xử lý ... <span class="caret"></span>';
                    $html .= '</button>';
                    $html .= '<ul class="dropdown-menu " style="right: 0; left:auto">';
                    $html .= '<li class="bg-blue" >' . Html::a('<span class="fa fa-pencil-square-o"></span>&nbsp;' . Yii::t('app', 'Edit'), \yii\helpers\Url::to(['invest-customer/update', 'id' => $data->id]), ['class' => '', 'title' => Yii::t('app', 'Edit')]) . '</li>';
                    $html .= '<li class="bg-aqua">';
                    if ($data->is_active == InvestCustomer::IS_ACTIVE_PENDING):
                        $html .= Html::a('<span class="fa fa-check-square-o"></span>&nbsp;' . Yii::t('app', 'Active'), \yii\helpers\Url::to(['invest-customer/active', 'id' => $data->id]), ['class' => '', 'title' => Yii::t('app', 'Active')]);
                    elseif ($data->is_active == InvestCustomer::IS_ACTIVE_COMPLETED):
                        $html .= Html::a('<span class="fa fa-minus-square-o"></span>&nbsp;' . Yii::t('app', 'Unactive'), \yii\helpers\Url::to(['invest-customer/unactive', 'id' => $data->id]), ['class' => '', 'title' => Yii::t('app', 'Unactive')]);
                    endif;
                    $html .= '</li>';
                    $html .= '<li class="bg-yellow">';
                    $html .= Html::a('<span class="fa fa-key"></span>&nbsp;' . Yii::t('app', 'Change Password'), \yii\helpers\Url::to(['invest-customer/change-password', 'id' => $data->id]), ['class' => '', 'title' => Yii::t('app', 'Change Password')]);
                    $html .= '</li>';
                    $html .= '<li class="bg-green">';
                    $html .= Html::a('<span class="fa fa-plus-square-o"></span>&nbsp;' . Yii::t('app', 'Add token'), \yii\helpers\Url::to(['invest-customer/transfer-token', 'id' => $data->id]), ['class' => '', 'title' => Yii::t('app', 'Add token')]);
                    $html .= '</li>';
                    $html .= '<li class="bg-blue">';
                    if ($data->status == InvestCustomer::STATUS_ACTIVE):
                        $html .= Html::a('<span class="fa fa-key"></span>&nbsp;' . Yii::t('app', 'Lock User'), \yii\helpers\Url::to(['invest-customer/lock-user', 'id' => $data->id]), ['class' => '', 'title' => Yii::t('app', 'Lock user')]);
                    elseif ($data->status == InvestCustomer::STATUS_INACTIVE):
                        $html .= Html::a('<span class="fa fa-key"></span>&nbsp;' . Yii::t('app', 'Unlock User'), \yii\helpers\Url::to(['invest-customer/lock-user', 'id' => $data->id]), ['class' => '', 'title' => Yii::t('app', 'Unlock user')]);
                    endif;
                    $html .= '</li>';

                    if ($data->bankAddress) {
                        $urlBankAddress = \yii\helpers\Url::to(['update-bank-address', 'id' => $data->id]);
                    } else {
                        $urlBankAddress = \yii\helpers\Url::to(['add-bank-address', 'id' => $data->id]);
                    }
                    $html .= '<li class="bg-maroon">';
                    $html .= Html::a('<span class="fa fa-btc"></span>&nbsp;' . Yii::t('app', 'Bank Address'), $urlBankAddress, [
                        'class' => '',
                    ]);
                    $html .= '</li>';

                    $html .= '</ul>';
                    $html .= '</div>';
                    return $html;
                },


            ]
        ],
    ];

    echo GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => $gridColumns,
        'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        //    'beforeHeader' => [
        //        [
        //            'columns' => [
        //                ['content' => 'Header Before 1', 'options' => ['colspan' => 4, 'class' => 'text-center warning']],
        //                ['content' => 'Header Before 2', 'options' => ['colspan' => 4, 'class' => 'text-center warning']],
        //                ['content' => 'Header Before 3', 'options' => ['colspan' => 3, 'class' => 'text-center warning']],
        //            ],
        //            'options' => ['class' => 'skip-export'] // remove this row from export
        //        ]
        //    ],
        'toolbar' => [
            '{export}',
            '{toggleData}'
        ],
        'exportConfig' => [
            GridView::CSV => ['label' => 'Save as CSV', 'filename' => Yii::t('customers', 'customerList') . date('Y-m-d', time()),],
            GridView::EXCEL => ['label' => 'Save as Excel', 'filename' => Yii::t('customers', 'customerList') . date('Y-m-d', time())],
            GridView::PDF => ['label' => 'Save as PDF', 'filename' => Yii::t('customers', 'customerList') . date('Y-m-d', time())],

        ],
        'export' => [
            'target' => GridView::TARGET_SELF,
        ],

        //    'target'=> ExportMenu::TARGET_SELF,

        'pjax' => true,
        'bordered' => true,
        'striped' => false,
        'condensed' => false,
        'responsive' => false,
        'responsiveWrap' => false,
        'persistResize' => false,
        'hover' => true,
        'floatHeader' => true,
        'floatHeaderOptions' => [],
        //    'floatHeaderOptions' => ['scrollingTop' => '50px'],
//            'showPageSummary' => true,
        'panel' => [
            'type' => GridView::TYPE_PRIMARY
        ],
    ]);

    ?>
</div>

<div class="modal fade" id="pageModal" tabindex="-1" role="dialog" aria-labelledby="pageModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
            </div>

        </div>
    </div>
</div>

<style>
    .add-note span {
        top: -15px !important;
        right: -10px !important;
    }

    .col-md-2.col-sm-3.col-xs-6 {
        width: 20% !important;
    }

    .dropdown-menu li a {
        color: #fff;
    }

    .dropdown-menu li a:hover {
        background: inherit;
    }
</style>