modules/admin/controllers/CustomerController.php
<?php

namespace app\modules\admin\controllers;

use app\components\controllers\AdminBaseController;
use app\forms\RegisterForm;
use app\models\CustomerBankAddress;
use app\models\CustomerCase;
use app\models\CustomerToken;
use app\models\LogAction;
use app\models\logs\AdminLogAction;
use app\models\Package;
use app\models\SystemEmailQueue;
use app\modules\admin\forms\AddMoneyForm;
use app\modules\admin\forms\AddTokenForm;
use app\modules\admin\forms\CashOutForm;
use app\modules\admin\forms\ChangePasswordForm;
use app\modules\admin\forms\CustomerLoan;
use app\modules\admin\forms\CustomerLoanForm;
use app\modules\admin\forms\customers\TransferTokenForm;
use app\modules\customer\forms\search\CustomerBankAddressSearch;
use Yii;
use app\models\Customer;
use app\modules\admin\forms\search\CustomerSearch;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\CustomerPackage;

/**
 * CustomerController implements the CRUD actions for Customer model.
 */
class CustomerController extends AdminBaseController
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Customer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CustomerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $allPackage = Package::findAll(['status' => Package::STATUS_ACTIVE]);
        $packages = ArrayHelper::map($allPackage, 'id', 'package_name');
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'packages' => $packages
        ]);
    }

    public function actionRequirePh($id)
    {
        $model = $this->findModel($id);
        $packages = $model->packages;
        $package = isset($packages[0]) ? $packages[0] : null;
        /*
         *  @var $package CustomerPackage
         */
        if (Yii::$app->request->post() && $package) {
            $required = Yii::$app->request->post('require', '');
            if ($required == "PH") {
                $transaction = Yii::$app->db->beginTransaction();
                try {
                    $package->reinvestment_date = time();
                    $package->is_reinvestment = CustomerPackage::PACKAGE_IS_REINVESTMENT;
                    $package->package_amount = $package->package_amount_root;
                    $package->status = CustomerPackage::STATUS_REQUEST_IN_STEP_ONE;
                    if ($package->save(true, ['status', 'package_amount', 'reinvestment_date', 'is_reinvestment', 'updated_at'])) {
                        $model->is_invest = Customer::INVESTED;
                        if ($model->save(true, ['is_invest', 'updated_at'])) {
                            //Tạo gói đầu tư rồi giờ tạo request
                            $result = $package->requestOpenPackage();
                            if ($result["status"] == "success") {
                                //sent email
                                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_CREATE, $model->attributes);
                                $transaction->commit();
                                $params = $package->getAttributes(['id', 'package_name', 'package_amount', 'increase_amount']);
                                $params["username"] = $model->username;
                                SystemEmailQueue::createEmailQueue(
                                    SystemEmailQueue::TYPE_CUSTOMER_RE_OPEN_PACKAGE,
                                    $model->email,
                                    'You receiver 1 request completed ' . $package->package_name . ' at' . Yii::$app->formatter->asDatetime(time()),
                                    're-open-package-completed',
                                    $params
                                );

                                Yii::$app->session->setFlash('success', 'Request member GH to system');
                                return $this->redirect(['customer-transaction-queue/index']);
                            } else {
                                Yii::$app->session->setFlash('error', 'Request member GH to system error');

                            }
                        }

                    }
                } catch (\Exception $ex) {
                    $transaction->rollBack();
                    AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_ERROR, $model->attributes);
                    Yii::$app->session->setFlash('error', 'Request member GH to system error');
                }


            }
        }
        return $this->render('require-ph', [
            'model' => $model,
            'package' => $package
        ]);
    }

    /**
     * Creates a new Customer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($ref = null)
    {
        $model = new RegisterForm();
        $model->scenario = $model::SCENARIO_ADMIN_REGISTER;
        $listCustomer = null;
        if ($ref) {
            $customerInvited = Customer::findByRefCode($ref);
            if (!$customerInvited) {
                throw new NotFoundHttpException('Tài khoản giới thiệu không hợp lệ.');
            }
            $model->customer_parent_id = $customerInvited->id;
        } else {
            $listCustomer = Customer::getAllCustomer(0, Customer::TYPE_ADMIN);
        }

        if ($model->load(Yii::$app->request->post())) {
            $customer = $model->createCustomer(true);
            $errors = $customer->getErrors();
            if (empty($errors)) {
                //Add case
                if ($customer->addCustomerCase()) {
//                    LogAction::logAdmin($customer->id, $customer::tableName(), LogAction::TYPE_USER_CREATE, $customer->getAttributes(['id', 'username', 'full_name', 'sex', 'phone', 'email', 'date_join', 'created_at']));
                    AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_CREATE, $customer->attributes);
                } else {
                    //Nếu có lỗi xóa tài khoản đi
                    $customer->delete();
                }
                return $this->redirect(['index']);
            } else {
                if (!empty($errors)) {
                    print_r($customer->getErrors());
                }
            }

        }
        return $this->render('create', [
            'model' => $model,
            'listCustomer' => $listCustomer
        ]);
    }

    /**
     * Updates an existing Customer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $old_parent_id = $model->parent_id;
        if ($model->load(Yii::$app->request->post())) {
            $model->parent_id = $old_parent_id;
            if ($model->save(true, ["status", "date_join", "full_name", "sex", "dob", "phone", "email", "nation", "address", "updated_at"])) {
                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_UPDATE, $model->attributes);
                return $this->redirect(['index']);
            }
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Customer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model->created_type == Customer::TYPE_ADMIN) {
            $model->is_deleted = $model::IS_DELETED;
            if ($model->save(true, ['is_deleted', 'updated_at'])) {
                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_DELETE, $model->attributes);

                Yii::$app->session->setFlash('success', 'You are deleted user: "' . $model->username . '" successfull.');
            } else {

                Yii::$app->session->setFlash('error', 'You not deleted user: "' . $model->username . '".');
            }
        } else {
            Yii::$app->session->setFlash('error', 'You not deleted user: "' . $model->username . '".');
        }
//        Customer::saveCustomerCaseDelete($model->id, $model->parent_id);
        return $this->redirect(['index']);
    }

    /**
     * Finds the Customer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Customer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Customer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionChangePassword($id)
    {
        $user = $this->findModel($id);
        $model = new ChangePasswordForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $user->setPassword($model->newPassword);
                $user->generateAuthKey();
                if ($user->save()) {
                    AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_UPDATE, $model->attributes);
                    Yii::$app->session->setFlash('success', Yii::t('customers', 'Change password completed'));
                    $this->redirect(['index']);
                }
            }
        }
        return $this->render('change-password', [

modules/admin/controllers/StatisticController.php
<?php

namespace app\modules\admin\controllers;

use app\components\controllers\AdminBaseController;
use app\models\Customer;
use app\models\CustomerRequireCashout;
use app\modules\admin\forms\search\CustomerRequireCashoutSearch;
use app\modules\admin\forms\search\CustomerSearch;
use Yii;
use yii\data\ArrayDataProvider;
use yii\db\Query;

class StatisticController extends AdminBaseController
{

    public function actionStatisticCustomerJoin()
    {
        $modelSearch = new CustomerSearch();
        $data = $modelSearch->statisticCutomerJoin(Yii::$app->request->queryParams);
        return $this->render('statistic-customer-register', [
            'data' => $data,
            'modelSearch' => $modelSearch
        ]);
    }

    public function actionStatisticTotalCashout()
    {
        $query = (new Query());
        $query->select(['c.id', 'c.username', 'c.full_name', 'c.package_id', 'c.amount', 'c.status', 'c.date_join', 'c.last_auto_increase', 'COUNT(crs.id) as total_required', 'SUM(crs.amount) as total_amount']);
        $query->from(Customer::tableName() . ' c');
        $query->leftJoin(CustomerRequireCashout::tableName() . ' crs', 'crs.customer_id= c.id AND crs.status=' . CustomerRequireCashout::STATUS_PENDING);

        $query->where(['!=', 'c.is_deleted', Customer::IS_DELETED]);
        $isSystemAdmin = Yii::$app->authManager->getAssignment(RBAC_FULL, Yii::$app->user->id);
        if (!$isSystemAdmin) {
            $query->andWhere(['c.user_id_first_branch' => Customer::ID_ONLY_VIEW]);
        }
        $query->groupBy(['c.id']);
        $dataTotal = (new Query())
            ->select(['COUNT(id) as total_customer', 'SUM(total_required) as total_required', 'SUM(total_amount) as total_amount'])
            ->from(['tbl'=>$query])
            ->one();
        $dataProvider = new ArrayDataProvider([
            'allModels' => $query->all(),
//            'sort' => [
//                'defaultOrder' => [
//                    'c.username' => SORT_ASC,
//                ]
//            ],
            'pagination' => [
                'pageSize' => 30
            ]

        ]);


        return $this->render('statistic-customer-cashout', [
            'dataProvider' => $dataProvider,
            'dataTotal' => $dataTotal
        ]);
    }

    public function  actionStatisticCustomerRequest()
    {
        $modelSearch = new CustomerRequireCashoutSearch();
        $dataProvider = $modelSearch->statisticCutomerPending(Yii::$app->request->queryParams);
        $dataTotal = $modelSearch->getCustomerRequestCashOut();
        return $this->render('statistic-require-cashout', [
            'dataProvider' => $dataProvider,
            'modelSearch' => $modelSearch,
            'dataTotal' => $dataTotal
        ]);
    }

}

modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use app\components\controllers\AdminBaseController;
use app\models\Customer;
use app\models\logs\AdminLogAction;
use app\models\permissions\AuthAssignment;
use Yii;
use yii\web\NotFoundHttpException;
use app\modules\admin\forms\UserSearch;
use app\models\User;
use app\models\permissions\AuthItem;

class UserController extends AdminBaseController
{

    public function actionCreate()
    {
        $model = new User();
        if ($model->load(Yii::$app->request->post())) {
            $model->setPassword($model->password_hash);
            $model->generateAuthKey();
//            $model->created_type=Customer::TYPE_ADMIN;
//            $model->created_by=Yii::$app->user->id;
            if ($model->save()) {
                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_CREATE, $model->attributes);
                Yii::$app->session->setFlash('success', Yii::t('users', 'Create new user completed.'));
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            $attributeValidate = ['status', 'email', 'updated_at', 'full_name', 'phone'];
            if ($model->password_hash) {
                $model->setPassword($model->password_hash);
                $attributeValidate[] = 'password_hash';
                $attributeValidate[] = 'auth_key';

            }
            if ($model->save(true, $attributeValidate)) {
                AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_UPDATE, $model->attributes);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionView($id)
    {
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->status = User::IS_DELETED;
        if ($model->save(true, ['status', 'updated_at'])) {
            AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_DELETE, $model->attributes);
            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the BannerSystem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return BannerSystem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            if ($model->username == Yii::$app->params["HIDDEN_ADMIN"] && Yii::$app->user->identity->username != Yii::$app->params["HIDDEN_ADMIN"]) {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Phân quyền cho quản trị
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionPermission($id)
    {
        $model = $this->findModel($id);

        $auth = Yii::$app->authManager;

        // Lấy các quyền được gán cho user
        $assignments = $auth->getAssignments($model->id);
        $selected = array_keys($assignments);

        if (Yii::$app->request->isPost && ($data = Yii::$app->request->post('data')) !== null) {
            $authAssignmentModel = new AuthAssignment();
            $authAssignmentModel->set($data, $model->id);
            Yii::$app->cache->delete('rbac');
            AdminLogAction::createLogAction(AdminLogAction::ACTION_TYPE_UPDATE, $model->attributes);
            Yii::$app->session->setFlash('success', Yii::t('users', 'Set permission for user completed'));
            return $this->refresh();
        }

        return $this->render('permission', [
            'model' => $model,
            'items' => AuthItem::getItems(),
            'selected' => $selected,
        ]);
    }

}

modules/admin/views/default/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
$this->params['pageTitle'] = $this->title;
$this->params['pageDescription'] = $message;
?>
<div class="site-error">
    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>
    <?php if (YII_DEBUG == 3) : ?>
<!--        <pre>--><?php //print_r($exception); ?><!--</pre>-->
    <?php endif; ?>
</div>

modules/admin/views/default/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */

$this->title = Yii::t('app','Admin Page');
$this->params['pageTitle'] = $this->title;
?>
<div class="row default-admin">
    <div class="col-md-4">
        <div class="info-box">
            <?= Html::a('<span class="info-box-icon bg-aqua"><i class="fa fa-sitemap"></i></span>', ['customer/index'])?>
            <div class="info-box-content">
                <span class="info-box-text">
                    <?= Html::a(Yii::t('app','Customer manager'), ['customer/index'])?>
                </span>
                <!--<span class="info-box-number">93,139</span>-->
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="info-box">
            <?= Html::a('<span class="info-box-icon bg-red"><i class="fa fa-usd"></i></span>', ['withdrawal/index'])?>
            <div class="info-box-content">
                <span class="info-box-text">
                    <?= Html::a(Yii::t('app','Request withdrawal'), ['withdrawal/index'])?>
                </span>
                <!--<span class="info-box-number">3,139</span>-->
            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="info-box">
            <?= Html::a('<span class="info-box-icon bg-yellow"><i class="fa fa-exchange"></i></span>', ['transaction/index'])?>
            <div class="info-box-content">
                <span class="info-box-text">
                    <?= Html::a(Yii::t('app',' Transactions history'), ['transaction/index'])?>
                </span>
                <!--<span class="info-box-number">3,139</span>-->
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="info-box">
            <?= Html::a('<span class="info-box-icon bg-green"><i class="fa fa-pie-chart"></i></span>', ['report/index'])?>
            <div class="info-box-content">
                <span class="info-box-text">
                    <?= Html::a(Yii::t('app','Statistics'), ['statistic/statistic-total-cashout'])?>
                </span>
                <!--<span class="info-box-number">3,139</span>-->
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="info-box">
            <?= Html::a('<span class="info-box-icon bg-maroon"><i class="fa fa-gears"></i></span>', ['user/index'])?>
            <div class="info-box-content">
                <span class="info-box-text">
                    <?= Html::a(Yii::t('app',' System Manager'), ['user/index'])?>
                </span>
                <!--<span class="info-box-number">3,139</span>-->
            </div>
        </div>
    </div>


</div>

modules/admin/views/default/login.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\modules\admin\forms\LoginForm */

$this->title = 'Login';

?>
<div class="site-login" style="text-align: center">
    <h1 class="title-login"><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-sm-2"></div>
        <div class="login-form-border col-sm-8 col-xs-12" style="padding-bottom: 10px;">
            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
                'options' => ['class' => 'form-horizontal'],
                'fieldConfig' => [
                    'template' => "<div>{input}</div>",
                    'labelOptions' => ['class' => 'col-lg-1 control-label'],
                ],
            ]); ?>

            <?= $form->field($model, 'username')->textInput(['placeholder' => 'Username / Email']) ?>

            <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Password']) ?>

            <?= $form->field($model, 'rememberMe')->checkbox([
                'template' => "<div class=\"text-left\">{input} {label}</div>",
            ]) ?>

            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn', 'name' => 'login-button', 'style' => 'background-color:#f44336; color:#fff']) ?>
                <?= Html::resetButton('Clear', ['class' => 'btn', 'name' => 'login-button', 'style' => 'background-color:#959595; color:#fff']) ?>

            </div>


            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-sm-2"></div>

    </div>
    <?php /*
     <div class="row">
            <div class="register-button">
                <?= Html::a('Register', ['register'], ['class' => 'btn btn-xs btn-register']) ?>
                <?= Html::a('Forget Password', ['forget-password'], ['class' => 'btn btn-xs btn-register']) ?>
            </div>
        </div>
     */ ?>
</div>