modules/invest/controllers/CustomerTokenController.php
<?php

namespace app\modules\invest\controllers;

use app\components\controllers\InvestBaseController;
use app\forms\CustomerTokenTransactionSearch;
use app\forms\ExchangeTokenForm;
use app\models\CustomerTokenTransaction;
use Yii;
use app\models\CustomerToken;
use app\forms\CustomerTokenSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CustomerTokenController implements the CRUD actions for CustomerToken model.
 */
class CustomerTokenController extends InvestBaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CustomerToken models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CustomerTokenSearch();
        $params = Yii::$app->request->queryParams;
        $params['CustomerTokenSearch']['customer_id'] = Yii::$app->user->identity->id;
        $params['CustomerTokenSearch']['type'] = CustomerToken::TYPE_INVEST;
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CustomerToken model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CustomerToken model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
//        $model = new CustomerToken();
//
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        } else {
//            return $this->render('create', [
//                'model' => $model,
//            ]);
//        }
    }

    /**
     * Updates an existing CustomerToken model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
//        $model = $this->findModel($id);
//
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        } else {
//            return $this->render('update', [
//                'model' => $model,
//            ]);
//        }
    }

    /**
     * Deletes an existing CustomerToken model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
//        $this->findModel($id)->delete();
//
//        return $this->redirect(['index']);
    }

    /**
     * Finds the CustomerToken model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CustomerToken the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CustomerToken::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionExchange()
    {
        $model = new ExchangeTokenForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->type = CustomerToken::TYPE_INVEST;
            if ($model->validate()) {
                $result = $model->process();
                if (isset($result["status"]) && $result["status"] == "success") {
                    Yii::$app->session->setFlash('success', 'You sent ' . $model->quantity . ' token to customer code ' . $model->customer_username);
                    return $this->redirect(['index']);
                } else {
                    Yii::$app->session->setFlash('error', $result["message"]);
                }
            }
        }
        return $this->render('exchange', ['model' => $model]);
    }

    public function actionTransactionHistory(){
        $searchModel = new CustomerTokenTransactionSearch();
        $params = Yii::$app->request->queryParams;
        $params['CustomerTokenTransactionSearch']['customer_id'] = Yii::$app->user->identity->id;
        $params['CustomerTokenTransactionSearch']['type_module'] = CustomerTokenTransaction::TYPE_MODULE_INVEST;
        $dataProvider = $searchModel->search($params);

        return $this->render('transaction/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

}

modules/invest/controllers/MyAccountController.php
<?php

namespace app\modules\invest\controllers;

use app\models\investments\InvestCustomerBankAddress;
use app\models\investments\InvestCustomerCase;
use app\models\searchs\InvestCustomerBankAddressSearch;
use app\modules\invest\forms\packages\RegisterForm;
use app\components\controllers\CustomerBaseController;
use app\components\controllers\InvestBaseController;
use app\models\CustomerActivity;
use app\models\CustomerBankAddress;
use app\models\CustomerOrder;
use app\models\CustomerPackage;
use app\models\CustomerPoundageTransaction;
use app\models\CustomerRequireCashout;
use app\models\CustomerToken;
use app\models\CustomerTransaction;
use app\models\investments\InvestCustomer;
use app\models\investments\InvestCustomerPackage;
use app\models\investments\InvestCustomerRequest;
use app\models\investments\InvestCustomerTransaction;
use app\models\investments\InvestCustomerWallet;
use app\models\investments\InvestPackage;
use app\models\LogAction;
use app\models\searchs\CustomerOrderSearch;
use app\models\searchs\CustomerTokenSearch;
use app\modules\invest\forms\packages\SetParentForm;
use app\modules\invest\forms\requests\ActiveWalletForm;
use \app\modules\invest\forms\requests\CashOutForm;
use app\modules\customer\forms\ChangePasswordForm;
use app\modules\customer\forms\CustomerActiveForm;
use \app\modules\invest\forms\requests\CustomerProviderHelpForm;
use app\modules\customer\forms\CustomerTransactionSearch;
use app\modules\invest\forms\Orders\BuyTokenForm;
use app\modules\invest\forms\Orders\PaymentOrderForm;
use app\modules\customer\forms\search\CustomerBankAddressSearch;
use app\modules\customer\forms\search\CustomerCaseSearch;
use app\modules\customer\forms\search\CustomerRequireCashoutSearch;
use app\modules\invest\forms\packages\UpgradePackageForm;
use Yii;
use app\models\Customer;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Package;
use yii\web\UploadedFile;


/**
 * MyAccountController implements the CRUD actions for Customer model.
 */
class MyAccountController extends InvestBaseController
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
//                    'active-by-current-token' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Customer models.
     * @return mixed
     */
    public function actionIndex()
    {

        //return $this->redirect(['default/index']);
        $model = Yii::$app->user->identity;
        return $this->render('index', ['model' => $model]);
    }

    /**
     * Displays a single Customer model.
     * @param string $id
     * @return mixed
     */
    public function actionView()
    {
        return $this->render('view', [
            'model' => $this->findModel(Yii::$app->user->id),
        ]);
    }


    /**
     * Updates an existing Customer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate()
    {

        $model = $this->findModel(Yii::$app->user->id);
        $packageList = ArrayHelper::map(Package::getPackages(Yii::$app->user->identity->amount), 'id', 'package_name');
        $accountInvite = ArrayHelper::map(Customer::getAccountInBranch(Yii::$app->user->id), 'id', 'username');
        if ($model->load(Yii::$app->request->post()) && $model->save(true, [
                'full_name',
                'phone',
                'sex',
                'dob',
                'email',
                'address',
                'upated_at'
            ])
        ) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
                'packageList' => $packageList,
                'accountInvite' => $accountInvite
            ]);
        }
    }

    /**
     * Deletes an existing Customer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public
    function actionDelete($id)
    {
//        $this->findModel($id)->delete();
//
//        return $this->redirect(['index']);
    }

    /**
     * Finds the Customer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Customer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Customer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionChangePassword()
    {
//        $user= $this->findModel($id);
        $model = new \app\modules\invest\forms\ChangePasswordForm();
        $model->currentPassword = '';
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate() && $model->changePassword()) {
                Yii::$app->session->setFlash('success', Yii::t('customers', 'Update new password completed.'));
                $this->redirect(['index']);
            } else {

            }
        }
        return $this->render('change-password', [
            'model' => $model
        ]);
    }


    public function actionMyBank()
    {
        $searchModel = new InvestCustomerBankAddressSearch();
        $queryParams = Yii::$app->request->queryParams;
        $queryParams['InvestCustomerBankAddressSearch']['invest_customer_id'] = Yii::$app->user->id;
        $dataProvider = $searchModel->search($queryParams);

        return $this->render('banks/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreateAddressBank()
    {
        if (Yii::$app->user->identity->bankAddress) {
            throw new BadRequestHttpException ('The request not exactly!');
        }
        $model = new InvestCustomerBankAddress();

        if ($model->load(Yii::$app->request->post())) {
            $model->invest_customer_id = Yii::$app->user->id;
            if ($model->save()) {
                return $this->redirect(['my-bank', 'id' => $model->id]);
            }
        }
        return $this->render('banks/create', [
            'model' => $model,
        ]);
    }


    public function actionMember($next = 0)
    {
        $id = Yii::$app->user->id;
        if ($next) {// check có phải là con của bản than ko
            if ($next == $id) {
                $id = $next;
            } else {
                $chk = (new Query())->select('*')->from(InvestCustomerCase::tableName())->where([
                    'parent_id' => $id,
                    'customer_id' => $next
                ])->count();
                if (!$chk) {
                    throw new NotFoundHttpException(Yii::t('messages', 'Yêu cầu không tồn tại.'));
                }
                $id = $next;
            }

        }

        $model = InvestCustomer::showTree($id, 3, false);
        return $this->render('members/index-2', ['model' => $model]);
    }

    public function actionMember2()
    {
        $model = InvestCustomer::showTree(Yii::$app->user->id, 10, false);
        return $this->render('members/index-2', ['model' => $model]);
    }

    public function actionBuyToken()
    {
        $model = new BuyTokenForm();
        $model->customer_id = Yii::$app->user->identity->id;
        if ($model->load(Yii::$app->request->post())) {
            $order = $model->buy();
            if ($order && isset($order->id) && $order->id) {
                Yii::$app->session->setFlash('success', Yii::t('messages', 'Bạn đã mua ') . $order->quantity . ' token! ');
                return $this->redirect(['check-out', 'id' => $order->id]);
            } else {
                Yii::$app->session->setFlash('success', Yii::t('messages', 'Bạn không đặt mua được ') . $order->quantity . ' token! ');
            }
        }
        return $this->render('orders/buy-token', ['model' => $model]);
    }

    public function actionCheckOut($id)
    {
        $model = CustomerOrder::findOne([
            'id' => $id,
            'customer_id' => Yii::$app->user->identity->id,
            'type_module' => CustomerOrder::TYPE_MODULE_INVEST
        ]);
        if (!$model) {
            throw new NotFoundHttpException(Yii::t('messages', 'Yêu cầu không tồn tại.'));
        }
        if (Yii::$app->request->isAjax) {
            $type = Yii::$app->request->post('type', '');
            switch ($type) {
                case 'remove-image':
                    $result = $model->removeAttachment();
                    return $result;

                    break;
                default:
                    break;

            }
            return false;
        }
        $modelForm = new PaymentOrderForm();
        $modelForm->order_id = $model->id;
        if ($modelForm->load(Yii::$app->request->post())) {
            $modelForm->file = UploadedFile::getInstance($modelForm, 'file');

            if ($modelForm->validate('file')) {
                $uploadDir = 'orders/invest/' . Yii::$app->user->id;
                $model->attachment = Yii::$app->image->upload(0, $uploadDir, $modelForm->file);
                $model->upload_attachment_at = time();
                if ($model->attachment) {

                    $model->status = CustomerOrder::STATUS_PAID;
                    if ($model->save(true, ['attachment', 'upload_attachment_at', 'status', 'updated_at'])) {

modules/invest/views/customer-token/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CustomerToken */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="customer-token-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'token')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'customer_id')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'type')->textInput() ?>

    <?= $form->field($model, 'expired_at')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/invest/views/customer-token/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\forms\CustomerTokenSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="customer-token-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'token') ?>

    <?= $form->field($model, 'customer_id') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'expired_at') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/invest/views/customer-token/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\CustomerToken */

$this->title = Yii::t('app', 'Create Customer Token');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Customer Tokens'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customer-token-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/invest/views/customer-token/exchange.php
<?php
/**
 * Created by PhpStorm.
 * User: vinhhx
 * Date: 16-Jul-16
 * Time: 2:00 AM
 */
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = Yii::t('app', 'Transfer Token');
$this->params['breadcrumbs'][Yii::t('app', 'Tokens')] = \yii\helpers\Url::to(['index']);
$this->params['breadcrumbs'][] = $this->title;
$this->params['pageTitle'] = $this->title;
$this->params['parentAction'] = '/customer/my-account/index';

?>
<div class="box-body">
    <?php $form = ActiveForm::begin([
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-sm-3',
                'offset' => 'col-sm-offset-0',
                'wrapper' => 'col-sm-9',
                'error' => 'col-sm-9',
                'hint' => 'col-sm-9',
            ],

        ]
    ]); ?>
    <?php
    $countToken = Yii::$app->user->identity->countCurrentToken();
    if($countToken<1):
    ?>
    <div class="form-group">
        <label class="control-label col-sm-3 text-red"
               for="button-submit"><?= Yii::t('customers', 'System Notice') ?></label>

        <div class="col-sm-6">
            <label class="form-control color-red"
                   style="border: none;"><?= Yii::t('customers', 'Number token  not enough to exchange'); ?></label>
        </div>
    </div>
    <?php endif; ?>
    <div class="form-group">
        <label class="control-label col-sm-3"
               for="button-submit"><?= Yii::t('customers', 'Rút tối thiểu') ?></label>

        <div class="col-sm-6">
            <label class="form-control"
                   style="border: none;"><?= 1 ?></label>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3"
               for="button-submit"><?= Yii::t('investment', 'Number current token') ?></label>

        <div class="col-sm-6">
                <span class="text-bold text-primary form-control"
                      style="border:none"><?= Yii::$app->formatter->asInteger($countToken) ?>
                    &nbsp;Token</span>
        </div>
    </div>
    <?= $form->field($model, 'customer_username')->textInput(['placeholder' => Yii::t('investment', 'Customer username'), 'class' => 'form-control', 'style' => 'width:500px;', 'maxlength' => true]); ?>

    <?= $form->field($model, 'quantity')->textInput(['placeholder' => Yii::t('investment', 'Number token'), 'class' => 'form-control', 'style' => 'width:250px;', 'maxlength' => true]); ?>
    <?= $form->field($model, 'password')->passwordInput(['placeholder' => Yii::t('investment', 'Current Password'), 'class' => 'form-control', 'style' => 'width:250px;', 'maxlength' => true]); ?>
    <div class="form-group">
        <label class="control-label col-sm-3" for="button-submit"></label>

        <div class="col-sm-6">
            <?php $disabled= ($countToken)?false:true; ?>
            <?= \yii\helpers\Html::submitButton('<span class="fa fa-money"></span>&nbsp;' . Yii::t('investment', 'Gửi'), ['class' => 'btn btn-sm btn-success','disabled'=>$disabled]) ?>
            <?php if($disabled): ?>
                <?= Html::a('<i class="fa fa-plus-square-o"></i>&nbsp;' . Yii::t('app', 'Buy Token'), ['my-account/buy-token'], ['class' => 'btn btn-primary btn sm']) ?>
            <?php endif; ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

modules/invest/views/customer-token/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\forms\CustomerTokenSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Customer Tokens');
$this->params['breadcrumbs']["Account"] = \yii\helpers\Url::to(['my-account/index']);
$this->params['pageTitle'] = $this->title;
?>
<div class="customer-token-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>

        <?= Html::a('<i class="fa fa-exchange"></i>&nbsp;' .Yii::t('app', 'Transfer token'), ['exchange'], ['class' => 'btn btn-warning']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'options' => ['class' => 'grid-view grid-view-customize'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'token',
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function ($model) {
                    return '<span class="'.(($model->status==\app\models\CustomerToken::STATUS_USED)? 'text-red':'text-green').'">'. $model->getStatusLabel().'</span>';
                }

            ],
             'created_at:datetime',
            // 'updated_at',

//            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

modules/invest/views/customer-token/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CustomerToken */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Customer Token',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Customer Tokens'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="customer-token-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/invest/views/customer-token/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\CustomerToken */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Customer Tokens'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customer-token-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'token',
            'customer_id',
            'status',
            'type',
            'expired_at',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>